# name of the program (Minix service)
PROG=proj

# source code files to be compiled
SRCS = proj.c videocard.c sprite.c KeyBoard.c utils.c Player.c

# additional compilation flags
# "-Wall -Wextra -Werror -I . -std=c11 -Wno-unused-parameter" are already set
CPPFLAGS += -pedantic

# list of library dependencies (for Proj, only LCF library)
DPADD += ${LIBLCF}
LDADD += -llcf

# include LCOM's makefile that does all the "heavy lifting"
.include <minix.lcom.mk>
